version: "3"
services:
  app:
    container_name: denali_app
    build: .
    command: python main.py
  redis:
    image: redis
    ports:
      - "6379:6379"
  celery_worker:
    container_name: celery_worker
    build: 
      context: .
      # dockerfile: Dockerfile
    command: ["celery", "-A", "celery_config.tasks", "worker", "-l", "info", "--pool=eventlet"]
    depends_on:
      - redis
    # volumes:
    #   - ./:/app/
  flower:
    container_name: flower
    build: .
    command: celery -A celery_config.tasks flower -l info --pool=eventlet
    ports: 
      - "5555:5555"
    depends_on:
      - redis
      - celery_worker