# fly.toml app configuration file generated for denalibot-sparkling-mountain-5882 on 2023-12-20T18:07:07+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "denalibot-sparkling-mountain-5882"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
