# fly.toml app configuration file generated for denalibot-cool-log-748 on 2023-12-21T11:40:08+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "denalibot-cool-log-748"
primary_region = "ams"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 256
